/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppAvailabilityCreateRequestDataAttributes } from './appAvailabilityCreateRequestDataAttributes';
import { AppAvailabilityCreateRequestDataRelationships } from './appAvailabilityCreateRequestDataRelationships';

export class AppAvailabilityCreateRequestData {
    'type': AppAvailabilityCreateRequestData.TypeEnum;
    'attributes': AppAvailabilityCreateRequestDataAttributes;
    'relationships': AppAvailabilityCreateRequestDataRelationships;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppAvailabilityCreateRequestData.TypeEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppAvailabilityCreateRequestDataAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppAvailabilityCreateRequestDataRelationships"
        }    ];

    static getAttributeTypeMap() {
        return AppAvailabilityCreateRequestData.attributeTypeMap;
    }
}

export namespace AppAvailabilityCreateRequestData {
    export enum TypeEnum {
        AppAvailabilities = <any> 'appAvailabilities'
    }
}
