/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppPriceScheduleCreateRequestDataRelationships } from './appPriceScheduleCreateRequestDataRelationships';

export class AppPriceScheduleCreateRequestData {
    'type': AppPriceScheduleCreateRequestData.TypeEnum;
    'relationships': AppPriceScheduleCreateRequestDataRelationships;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppPriceScheduleCreateRequestData.TypeEnum"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppPriceScheduleCreateRequestDataRelationships"
        }    ];

    static getAttributeTypeMap() {
        return AppPriceScheduleCreateRequestData.attributeTypeMap;
    }
}

export namespace AppPriceScheduleCreateRequestData {
    export enum TypeEnum {
        AppPriceSchedules = <any> 'appPriceSchedules'
    }
}
