/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppPriceV2Attributes } from './appPriceV2Attributes';
import { AppPriceV2Relationships } from './appPriceV2Relationships';
import { ResourceLinks } from './resourceLinks';

export class AppPriceV2 {
    'type': AppPriceV2.TypeEnum;
    'id': string;
    'attributes'?: AppPriceV2Attributes;
    'relationships'?: AppPriceV2Relationships;
    'links': ResourceLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppPriceV2.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppPriceV2Attributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppPriceV2Relationships"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks"
        }    ];

    static getAttributeTypeMap() {
        return AppPriceV2.attributeTypeMap;
    }
}

export namespace AppPriceV2 {
    export enum TypeEnum {
        AppPrices = <any> 'appPrices'
    }
}
