/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppAvailabilityRelationshipsApp } from './appAvailabilityRelationshipsApp';
import { AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperience } from './appClipAppStoreReviewDetailRelationshipsAppClipDefaultExperience';
import { AppStoreReviewAttachmentRelationshipsAppStoreReviewDetail } from './appStoreReviewAttachmentRelationshipsAppStoreReviewDetail';
import { AppStoreVersionRelationshipsAppStoreVersionExperiments } from './appStoreVersionRelationshipsAppStoreVersionExperiments';
import { AppStoreVersionRelationshipsAppStoreVersionLocalizations } from './appStoreVersionRelationshipsAppStoreVersionLocalizations';
import { AppStoreVersionRelationshipsAppStoreVersionPhasedRelease } from './appStoreVersionRelationshipsAppStoreVersionPhasedRelease';
import { AppStoreVersionRelationshipsAppStoreVersionSubmission } from './appStoreVersionRelationshipsAppStoreVersionSubmission';
import { AppStoreVersionRelationshipsBuild } from './appStoreVersionRelationshipsBuild';
import { AppStoreVersionRelationshipsRoutingAppCoverage } from './appStoreVersionRelationshipsRoutingAppCoverage';

export class AppStoreVersionRelationships {
    'app'?: AppAvailabilityRelationshipsApp;
    'appStoreVersionLocalizations'?: AppStoreVersionRelationshipsAppStoreVersionLocalizations;
    'build'?: AppStoreVersionRelationshipsBuild;
    'appStoreVersionPhasedRelease'?: AppStoreVersionRelationshipsAppStoreVersionPhasedRelease;
    'routingAppCoverage'?: AppStoreVersionRelationshipsRoutingAppCoverage;
    'appStoreReviewDetail'?: AppStoreReviewAttachmentRelationshipsAppStoreReviewDetail;
    'appStoreVersionSubmission'?: AppStoreVersionRelationshipsAppStoreVersionSubmission;
    'appClipDefaultExperience'?: AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperience;
    'appStoreVersionExperiments'?: AppStoreVersionRelationshipsAppStoreVersionExperiments;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "app",
            "baseName": "app",
            "type": "AppAvailabilityRelationshipsApp"
        },
        {
            "name": "appStoreVersionLocalizations",
            "baseName": "appStoreVersionLocalizations",
            "type": "AppStoreVersionRelationshipsAppStoreVersionLocalizations"
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "AppStoreVersionRelationshipsBuild"
        },
        {
            "name": "appStoreVersionPhasedRelease",
            "baseName": "appStoreVersionPhasedRelease",
            "type": "AppStoreVersionRelationshipsAppStoreVersionPhasedRelease"
        },
        {
            "name": "routingAppCoverage",
            "baseName": "routingAppCoverage",
            "type": "AppStoreVersionRelationshipsRoutingAppCoverage"
        },
        {
            "name": "appStoreReviewDetail",
            "baseName": "appStoreReviewDetail",
            "type": "AppStoreReviewAttachmentRelationshipsAppStoreReviewDetail"
        },
        {
            "name": "appStoreVersionSubmission",
            "baseName": "appStoreVersionSubmission",
            "type": "AppStoreVersionRelationshipsAppStoreVersionSubmission"
        },
        {
            "name": "appClipDefaultExperience",
            "baseName": "appClipDefaultExperience",
            "type": "AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperience"
        },
        {
            "name": "appStoreVersionExperiments",
            "baseName": "appStoreVersionExperiments",
            "type": "AppStoreVersionRelationshipsAppStoreVersionExperiments"
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionRelationships.attributeTypeMap;
    }
}

