/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppStoreVersionLocalization } from './appStoreVersionLocalization';
import { AppStoreVersionLocalizationsResponseIncludedInner } from './appStoreVersionLocalizationsResponseIncludedInner';
import { DocumentLinks } from './documentLinks';

export class AppStoreVersionLocalizationResponse {
    'data': AppStoreVersionLocalization;
    'included'?: Array<AppStoreVersionLocalizationsResponseIncludedInner>;
    'links': DocumentLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "AppStoreVersionLocalization"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<AppStoreVersionLocalizationsResponseIncludedInner>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "DocumentLinks"
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionLocalizationResponse.attributeTypeMap;
    }
}

