/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Platform } from './platform';

export class AppStoreVersionCreateRequestDataAttributes {
    'platform': Platform;
    'versionString': string;
    'copyright'?: string;
    'releaseType'?: AppStoreVersionCreateRequestDataAttributes.ReleaseTypeEnum;
    'earliestReleaseDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "platform",
            "baseName": "platform",
            "type": "Platform"
        },
        {
            "name": "versionString",
            "baseName": "versionString",
            "type": "string"
        },
        {
            "name": "copyright",
            "baseName": "copyright",
            "type": "string"
        },
        {
            "name": "releaseType",
            "baseName": "releaseType",
            "type": "AppStoreVersionCreateRequestDataAttributes.ReleaseTypeEnum"
        },
        {
            "name": "earliestReleaseDate",
            "baseName": "earliestReleaseDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionCreateRequestDataAttributes.attributeTypeMap;
    }
}

export namespace AppStoreVersionCreateRequestDataAttributes {
    export enum ReleaseTypeEnum {
        Manual = <any> 'MANUAL',
        AfterApproval = <any> 'AFTER_APPROVAL',
        Scheduled = <any> 'SCHEDULED'
    }
}
