/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppStoreVersionExperimentTreatmentLocalization } from './appStoreVersionExperimentTreatmentLocalization';
import { AppStoreVersionExperimentTreatmentLocalizationsResponseIncludedInner } from './appStoreVersionExperimentTreatmentLocalizationsResponseIncludedInner';
import { PagedDocumentLinks } from './pagedDocumentLinks';
import { PagingInformation } from './pagingInformation';

export class AppStoreVersionExperimentTreatmentLocalizationsResponse {
    'data': Array<AppStoreVersionExperimentTreatmentLocalization>;
    'included'?: Array<AppStoreVersionExperimentTreatmentLocalizationsResponseIncludedInner>;
    'links': PagedDocumentLinks;
    'meta'?: PagingInformation;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<AppStoreVersionExperimentTreatmentLocalization>"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<AppStoreVersionExperimentTreatmentLocalizationsResponseIncludedInner>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "PagedDocumentLinks"
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "PagingInformation"
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionExperimentTreatmentLocalizationsResponse.attributeTypeMap;
    }
}

