/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppAvailabilityCreateRequestDataRelationshipsApp } from './appAvailabilityCreateRequestDataRelationshipsApp';
import { AppStoreVersionCreateRequestDataRelationshipsAppStoreVersionLocalizations } from './appStoreVersionCreateRequestDataRelationshipsAppStoreVersionLocalizations';
import { AppStoreVersionCreateRequestDataRelationshipsBuild } from './appStoreVersionCreateRequestDataRelationshipsBuild';

export class AppStoreVersionCreateRequestDataRelationships {
    'app': AppAvailabilityCreateRequestDataRelationshipsApp;
    'appStoreVersionLocalizations'?: AppStoreVersionCreateRequestDataRelationshipsAppStoreVersionLocalizations;
    'build'?: AppStoreVersionCreateRequestDataRelationshipsBuild;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "app",
            "baseName": "app",
            "type": "AppAvailabilityCreateRequestDataRelationshipsApp"
        },
        {
            "name": "appStoreVersionLocalizations",
            "baseName": "appStoreVersionLocalizations",
            "type": "AppStoreVersionCreateRequestDataRelationshipsAppStoreVersionLocalizations"
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "AppStoreVersionCreateRequestDataRelationshipsBuild"
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionCreateRequestDataRelationships.attributeTypeMap;
    }
}

