/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppAvailabilityCreateRequestDataRelationshipsApp } from './appAvailabilityCreateRequestDataRelationshipsApp';
import { BetaGroupCreateRequestDataRelationshipsBetaTesters } from './betaGroupCreateRequestDataRelationshipsBetaTesters';
import { BetaGroupCreateRequestDataRelationshipsBuilds } from './betaGroupCreateRequestDataRelationshipsBuilds';

export class BetaGroupCreateRequestDataRelationships {
    'app': AppAvailabilityCreateRequestDataRelationshipsApp;
    'builds'?: BetaGroupCreateRequestDataRelationshipsBuilds;
    'betaTesters'?: BetaGroupCreateRequestDataRelationshipsBetaTesters;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "app",
            "baseName": "app",
            "type": "AppAvailabilityCreateRequestDataRelationshipsApp"
        },
        {
            "name": "builds",
            "baseName": "builds",
            "type": "BetaGroupCreateRequestDataRelationshipsBuilds"
        },
        {
            "name": "betaTesters",
            "baseName": "betaTesters",
            "type": "BetaGroupCreateRequestDataRelationshipsBetaTesters"
        }    ];

    static getAttributeTypeMap() {
        return BetaGroupCreateRequestDataRelationships.attributeTypeMap;
    }
}

