/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppPreOrderRelationships } from './appPreOrderRelationships';
import { BetaLicenseAgreementAttributes } from './betaLicenseAgreementAttributes';
import { ResourceLinks } from './resourceLinks';

export class BetaLicenseAgreement {
    'type': BetaLicenseAgreement.TypeEnum;
    'id': string;
    'attributes'?: BetaLicenseAgreementAttributes;
    'relationships'?: AppPreOrderRelationships;
    'links': ResourceLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "BetaLicenseAgreement.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "BetaLicenseAgreementAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppPreOrderRelationships"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks"
        }    ];

    static getAttributeTypeMap() {
        return BetaLicenseAgreement.attributeTypeMap;
    }
}

export namespace BetaLicenseAgreement {
    export enum TypeEnum {
        BetaLicenseAgreements = <any> 'betaLicenseAgreements'
    }
}
