/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CiTestStatus } from './ciTestStatus';

export class CiTestResultAttributesDestinationTestResultsInner {
    'uuid'?: string;
    'deviceName'?: string;
    'osVersion'?: string;
    'status'?: CiTestStatus;
    'duration'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "deviceName",
            "baseName": "deviceName",
            "type": "string"
        },
        {
            "name": "osVersion",
            "baseName": "osVersion",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CiTestStatus"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CiTestResultAttributesDestinationTestResultsInner.attributeTypeMap;
    }
}

export namespace CiTestResultAttributesDestinationTestResultsInner {
}
