/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CiMacOsVersion } from './ciMacOsVersion';
import { CiMacOsVersionAttributes } from './ciMacOsVersionAttributes';
import { CiMacOsVersionRelationships } from './ciMacOsVersionRelationships';
import { CiProduct } from './ciProduct';
import { CiXcodeVersion } from './ciXcodeVersion';
import { ResourceLinks } from './resourceLinks';
import { ScmRepository } from './scmRepository';

export class CiWorkflowsResponseIncludedInner {
    'type': CiWorkflowsResponseIncludedInner.TypeEnum;
    'id': string;
    'attributes'?: CiMacOsVersionAttributes;
    'relationships'?: CiMacOsVersionRelationships;
    'links': ResourceLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CiWorkflowsResponseIncludedInner.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "CiMacOsVersionAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "CiMacOsVersionRelationships"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks"
        }    ];

    static getAttributeTypeMap() {
        return CiWorkflowsResponseIncludedInner.attributeTypeMap;
    }
}

export namespace CiWorkflowsResponseIncludedInner {
    export enum TypeEnum {
        CiMacOsVersions = <any> 'ciMacOsVersions'
    }
}
