/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomerReviewResponseV1CreateRequestDataRelationshipsReview } from './customerReviewResponseV1CreateRequestDataRelationshipsReview';

export class CustomerReviewResponseV1CreateRequestDataRelationships {
    'review': CustomerReviewResponseV1CreateRequestDataRelationshipsReview;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "review",
            "baseName": "review",
            "type": "CustomerReviewResponseV1CreateRequestDataRelationshipsReview"
        }    ];

    static getAttributeTypeMap() {
        return CustomerReviewResponseV1CreateRequestDataRelationships.attributeTypeMap;
    }
}

