/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InAppPurchasePriceInlineCreateRelationshipsInAppPurchasePricePoint } from './inAppPurchasePriceInlineCreateRelationshipsInAppPurchasePricePoint';
import { InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2 } from './inAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2';

export class InAppPurchasePriceInlineCreateRelationships {
    'inAppPurchaseV2'?: InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2;
    'inAppPurchasePricePoint'?: InAppPurchasePriceInlineCreateRelationshipsInAppPurchasePricePoint;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inAppPurchaseV2",
            "baseName": "inAppPurchaseV2",
            "type": "InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2"
        },
        {
            "name": "inAppPurchasePricePoint",
            "baseName": "inAppPurchasePricePoint",
            "type": "InAppPurchasePriceInlineCreateRelationshipsInAppPurchasePricePoint"
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchasePriceInlineCreateRelationships.attributeTypeMap;
    }
}

