/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppAvailabilityAttributes } from './appAvailabilityAttributes';
import { InAppPurchaseAvailabilityRelationships } from './inAppPurchaseAvailabilityRelationships';
import { ResourceLinks } from './resourceLinks';

export class InAppPurchaseAvailability {
    'type': InAppPurchaseAvailability.TypeEnum;
    'id': string;
    'attributes'?: AppAvailabilityAttributes;
    'relationships'?: InAppPurchaseAvailabilityRelationships;
    'links': ResourceLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "InAppPurchaseAvailability.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppAvailabilityAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "InAppPurchaseAvailabilityRelationships"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks"
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchaseAvailability.attributeTypeMap;
    }
}

export namespace InAppPurchaseAvailability {
    export enum TypeEnum {
        InAppPurchaseAvailabilities = <any> 'inAppPurchaseAvailabilities'
    }
}
