/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppEventCreateRequestDataRelationships } from './appEventCreateRequestDataRelationships';
import { InAppPurchaseV2CreateRequestDataAttributes } from './inAppPurchaseV2CreateRequestDataAttributes';

export class InAppPurchaseV2CreateRequestData {
    'type': InAppPurchaseV2CreateRequestData.TypeEnum;
    'attributes': InAppPurchaseV2CreateRequestDataAttributes;
    'relationships': AppEventCreateRequestDataRelationships;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "InAppPurchaseV2CreateRequestData.TypeEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "InAppPurchaseV2CreateRequestDataAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppEventCreateRequestDataRelationships"
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchaseV2CreateRequestData.attributeTypeMap;
    }
}

export namespace InAppPurchaseV2CreateRequestData {
    export enum TypeEnum {
        InAppPurchases = <any> 'inAppPurchases'
    }
}
