/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InAppPurchaseAppStoreReviewScreenshot } from './inAppPurchaseAppStoreReviewScreenshot';
import { InAppPurchaseContent } from './inAppPurchaseContent';
import { InAppPurchaseLocalization } from './inAppPurchaseLocalization';
import { InAppPurchasePricePoint } from './inAppPurchasePricePoint';
import { InAppPurchasePriceSchedule } from './inAppPurchasePriceSchedule';
import { InAppPurchasePriceScheduleRelationships } from './inAppPurchasePriceScheduleRelationships';
import { PromotedPurchase } from './promotedPurchase';
import { PromotedPurchaseAttributes } from './promotedPurchaseAttributes';
import { ResourceLinks } from './resourceLinks';

export class InAppPurchasesV2ResponseIncludedInner {
    'type': InAppPurchasesV2ResponseIncludedInner.TypeEnum;
    'id': string;
    'attributes'?: PromotedPurchaseAttributes;
    'relationships'?: InAppPurchasePriceScheduleRelationships;
    'links': ResourceLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "InAppPurchasesV2ResponseIncludedInner.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "PromotedPurchaseAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "InAppPurchasePriceScheduleRelationships"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks"
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchasesV2ResponseIncludedInner.attributeTypeMap;
    }
}

export namespace InAppPurchasesV2ResponseIncludedInner {
    export enum TypeEnum {
        InAppPurchasePriceSchedules = <any> 'inAppPurchasePriceSchedules'
    }
}
