/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2 } from './inAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2';

export class InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationships {
    'inAppPurchaseV2': InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inAppPurchaseV2",
            "baseName": "inAppPurchaseV2",
            "type": "InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2"
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationships.attributeTypeMap;
    }
}

