/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InAppPurchaseState } from './inAppPurchaseState';
import { InAppPurchaseType } from './inAppPurchaseType';

export class InAppPurchaseV2Attributes {
    'name'?: string;
    'productId'?: string;
    'inAppPurchaseType'?: InAppPurchaseType;
    'state'?: InAppPurchaseState;
    'reviewNote'?: string;
    'familySharable'?: boolean;
    'contentHosting'?: boolean;
    'availableInAllTerritories'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "productId",
            "type": "string"
        },
        {
            "name": "inAppPurchaseType",
            "baseName": "inAppPurchaseType",
            "type": "InAppPurchaseType"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "InAppPurchaseState"
        },
        {
            "name": "reviewNote",
            "baseName": "reviewNote",
            "type": "string"
        },
        {
            "name": "familySharable",
            "baseName": "familySharable",
            "type": "boolean"
        },
        {
            "name": "contentHosting",
            "baseName": "contentHosting",
            "type": "boolean"
        },
        {
            "name": "availableInAllTerritories",
            "baseName": "availableInAllTerritories",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchaseV2Attributes.attributeTypeMap;
    }
}

export namespace InAppPurchaseV2Attributes {
}
