/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppAvailabilityCreateRequestDataRelationshipsApp } from './appAvailabilityCreateRequestDataRelationshipsApp';
import { InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2 } from './inAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2';
import { PromotedPurchaseCreateRequestDataRelationshipsSubscription } from './promotedPurchaseCreateRequestDataRelationshipsSubscription';

export class PromotedPurchaseCreateRequestDataRelationships {
    'app': AppAvailabilityCreateRequestDataRelationshipsApp;
    'inAppPurchaseV2'?: InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2;
    'subscription'?: PromotedPurchaseCreateRequestDataRelationshipsSubscription;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "app",
            "baseName": "app",
            "type": "AppAvailabilityCreateRequestDataRelationshipsApp"
        },
        {
            "name": "inAppPurchaseV2",
            "baseName": "inAppPurchaseV2",
            "type": "InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2"
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "PromotedPurchaseCreateRequestDataRelationshipsSubscription"
        }    ];

    static getAttributeTypeMap() {
        return PromotedPurchaseCreateRequestDataRelationships.attributeTypeMap;
    }
}

