/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2 } from './inAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2';
import { PromotedPurchaseRelationshipsPromotionImages } from './promotedPurchaseRelationshipsPromotionImages';
import { PromotedPurchaseRelationshipsSubscription } from './promotedPurchaseRelationshipsSubscription';

export class PromotedPurchaseRelationships {
    'inAppPurchaseV2'?: InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2;
    'subscription'?: PromotedPurchaseRelationshipsSubscription;
    'promotionImages'?: PromotedPurchaseRelationshipsPromotionImages;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inAppPurchaseV2",
            "baseName": "inAppPurchaseV2",
            "type": "InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2"
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "PromotedPurchaseRelationshipsSubscription"
        },
        {
            "name": "promotionImages",
            "baseName": "promotionImages",
            "type": "PromotedPurchaseRelationshipsPromotionImages"
        }    ];

    static getAttributeTypeMap() {
        return PromotedPurchaseRelationships.attributeTypeMap;
    }
}

