/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PromotedPurchaseAttributes {
    'visibleForAllUsers'?: boolean;
    'enabled'?: boolean;
    'state'?: PromotedPurchaseAttributes.StateEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "visibleForAllUsers",
            "baseName": "visibleForAllUsers",
            "type": "boolean"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "PromotedPurchaseAttributes.StateEnum"
        }    ];

    static getAttributeTypeMap() {
        return PromotedPurchaseAttributes.attributeTypeMap;
    }
}

export namespace PromotedPurchaseAttributes {
    export enum StateEnum {
        Approved = <any> 'APPROVED',
        InReview = <any> 'IN_REVIEW',
        PrepareForSubmission = <any> 'PREPARE_FOR_SUBMISSION',
        Rejected = <any> 'REJECTED'
    }
}
