/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships } from './subscriptionAppStoreReviewScreenshotCreateRequestDataRelationships';

export class SubscriptionSubmissionCreateRequestData {
    'type': SubscriptionSubmissionCreateRequestData.TypeEnum;
    'relationships': SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SubscriptionSubmissionCreateRequestData.TypeEnum"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionSubmissionCreateRequestData.attributeTypeMap;
    }
}

export namespace SubscriptionSubmissionCreateRequestData {
    export enum TypeEnum {
        SubscriptionSubmissions = <any> 'subscriptionSubmissions'
    }
}
