/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum SubscriptionOfferDuration {
    OneDay = <any> 'ONE_DAY',
    ThreeDays = <any> 'THREE_DAYS',
    OneWeek = <any> 'ONE_WEEK',
    TwoWeeks = <any> 'TWO_WEEKS',
    OneMonth = <any> 'ONE_MONTH',
    TwoMonths = <any> 'TWO_MONTHS',
    ThreeMonths = <any> 'THREE_MONTHS',
    SixMonths = <any> 'SIX_MONTHS',
    OneYear = <any> 'ONE_YEAR'
}
