/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ResourceLinks } from './resourceLinks';
import { SubscriptionPromotionalOfferAttributes } from './subscriptionPromotionalOfferAttributes';
import { SubscriptionPromotionalOfferRelationships } from './subscriptionPromotionalOfferRelationships';

export class SubscriptionPromotionalOffer {
    'type': SubscriptionPromotionalOffer.TypeEnum;
    'id': string;
    'attributes'?: SubscriptionPromotionalOfferAttributes;
    'relationships'?: SubscriptionPromotionalOfferRelationships;
    'links': ResourceLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SubscriptionPromotionalOffer.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "SubscriptionPromotionalOfferAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "SubscriptionPromotionalOfferRelationships"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionPromotionalOffer.attributeTypeMap;
    }
}

export namespace SubscriptionPromotionalOffer {
    export enum TypeEnum {
        SubscriptionPromotionalOffers = <any> 'subscriptionPromotionalOffers'
    }
}
