/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscriptionOfferCodeCustomCodeRelationshipsOfferCodeData } from './subscriptionOfferCodeCustomCodeRelationshipsOfferCodeData';

export class SubscriptionOfferCodeCustomCodeCreateRequestDataRelationshipsOfferCode {
    'data': SubscriptionOfferCodeCustomCodeRelationshipsOfferCodeData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "SubscriptionOfferCodeCustomCodeRelationshipsOfferCodeData"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionOfferCodeCustomCodeCreateRequestDataRelationshipsOfferCode.attributeTypeMap;
    }
}

