/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppAvailabilityRelationshipsAvailableTerritories } from './appAvailabilityRelationshipsAvailableTerritories';
import { PromotedPurchaseRelationshipsSubscription } from './promotedPurchaseRelationshipsSubscription';

export class SubscriptionAvailabilityRelationships {
    'subscription'?: PromotedPurchaseRelationshipsSubscription;
    'availableTerritories'?: AppAvailabilityRelationshipsAvailableTerritories;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "PromotedPurchaseRelationshipsSubscription"
        },
        {
            "name": "availableTerritories",
            "baseName": "availableTerritories",
            "type": "AppAvailabilityRelationshipsAvailableTerritories"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionAvailabilityRelationships.attributeTypeMap;
    }
}

