/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppClipAdvancedExperienceImageCreateRequestDataAttributes } from './appClipAdvancedExperienceImageCreateRequestDataAttributes';
import { SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships } from './subscriptionAppStoreReviewScreenshotCreateRequestDataRelationships';

export class SubscriptionAppStoreReviewScreenshotCreateRequestData {
    'type': SubscriptionAppStoreReviewScreenshotCreateRequestData.TypeEnum;
    'attributes': AppClipAdvancedExperienceImageCreateRequestDataAttributes;
    'relationships': SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SubscriptionAppStoreReviewScreenshotCreateRequestData.TypeEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppClipAdvancedExperienceImageCreateRequestDataAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionAppStoreReviewScreenshotCreateRequestData.attributeTypeMap;
    }
}

export namespace SubscriptionAppStoreReviewScreenshotCreateRequestData {
    export enum TypeEnum {
        SubscriptionAppStoreReviewScreenshots = <any> 'subscriptionAppStoreReviewScreenshots'
    }
}
