/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionAttributes {
    'name'?: string;
    'productId'?: string;
    'familySharable'?: boolean;
    'state'?: SubscriptionAttributes.StateEnum;
    'subscriptionPeriod'?: SubscriptionAttributes.SubscriptionPeriodEnum;
    'reviewNote'?: string;
    'groupLevel'?: number;
    'availableInAllTerritories'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "productId",
            "type": "string"
        },
        {
            "name": "familySharable",
            "baseName": "familySharable",
            "type": "boolean"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "SubscriptionAttributes.StateEnum"
        },
        {
            "name": "subscriptionPeriod",
            "baseName": "subscriptionPeriod",
            "type": "SubscriptionAttributes.SubscriptionPeriodEnum"
        },
        {
            "name": "reviewNote",
            "baseName": "reviewNote",
            "type": "string"
        },
        {
            "name": "groupLevel",
            "baseName": "groupLevel",
            "type": "number"
        },
        {
            "name": "availableInAllTerritories",
            "baseName": "availableInAllTerritories",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionAttributes.attributeTypeMap;
    }
}

export namespace SubscriptionAttributes {
    export enum StateEnum {
        MissingMetadata = <any> 'MISSING_METADATA',
        ReadyToSubmit = <any> 'READY_TO_SUBMIT',
        WaitingForReview = <any> 'WAITING_FOR_REVIEW',
        InReview = <any> 'IN_REVIEW',
        DeveloperActionNeeded = <any> 'DEVELOPER_ACTION_NEEDED',
        PendingBinaryApproval = <any> 'PENDING_BINARY_APPROVAL',
        Approved = <any> 'APPROVED',
        DeveloperRemovedFromSale = <any> 'DEVELOPER_REMOVED_FROM_SALE',
        RemovedFromSale = <any> 'REMOVED_FROM_SALE',
        Rejected = <any> 'REJECTED'
    }
    export enum SubscriptionPeriodEnum {
        OneWeek = <any> 'ONE_WEEK',
        OneMonth = <any> 'ONE_MONTH',
        TwoMonths = <any> 'TWO_MONTHS',
        ThreeMonths = <any> 'THREE_MONTHS',
        SixMonths = <any> 'SIX_MONTHS',
        OneYear = <any> 'ONE_YEAR'
    }
}
