/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PromotedPurchaseRelationshipsSubscription } from './promotedPurchaseRelationshipsSubscription';
import { SubscriptionOfferCodeRelationshipsCustomCodes } from './subscriptionOfferCodeRelationshipsCustomCodes';
import { SubscriptionOfferCodeRelationshipsOneTimeUseCodes } from './subscriptionOfferCodeRelationshipsOneTimeUseCodes';
import { SubscriptionOfferCodeRelationshipsPrices } from './subscriptionOfferCodeRelationshipsPrices';

export class SubscriptionOfferCodeRelationships {
    'subscription'?: PromotedPurchaseRelationshipsSubscription;
    'oneTimeUseCodes'?: SubscriptionOfferCodeRelationshipsOneTimeUseCodes;
    'customCodes'?: SubscriptionOfferCodeRelationshipsCustomCodes;
    'prices'?: SubscriptionOfferCodeRelationshipsPrices;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "PromotedPurchaseRelationshipsSubscription"
        },
        {
            "name": "oneTimeUseCodes",
            "baseName": "oneTimeUseCodes",
            "type": "SubscriptionOfferCodeRelationshipsOneTimeUseCodes"
        },
        {
            "name": "customCodes",
            "baseName": "customCodes",
            "type": "SubscriptionOfferCodeRelationshipsCustomCodes"
        },
        {
            "name": "prices",
            "baseName": "prices",
            "type": "SubscriptionOfferCodeRelationshipsPrices"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionOfferCodeRelationships.attributeTypeMap;
    }
}

