/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityRelationshipsAppLinks } from './AppAvailabilityRelationshipsAppLinks';
import {
    AppAvailabilityRelationshipsAppLinksFromJSON,
    AppAvailabilityRelationshipsAppLinksFromJSONTyped,
    AppAvailabilityRelationshipsAppLinksToJSON,
} from './AppAvailabilityRelationshipsAppLinks';
import type { BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsDataInner } from './BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsDataInner';
import {
    BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsDataInnerFromJSON,
    BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsDataInnerFromJSONTyped,
    BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsDataInnerToJSON,
} from './BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsDataInner';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';

/**
 * 
 * @export
 * @interface BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizations
 */
export interface BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizations {
    /**
     * 
     * @type {AppAvailabilityRelationshipsAppLinks}
     * @memberof BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizations
     */
    links?: AppAvailabilityRelationshipsAppLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizations
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsDataInner>}
     * @memberof BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizations
     */
    data?: Array<BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsDataInner>;
}

/**
 * Check if a given object implements the BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizations interface.
 */
export function instanceOfBetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizations(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsFromJSON(json: any): BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizations {
    return BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsFromJSONTyped(json, false);
}

export function BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityRelationshipsAppLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsDataInnerFromJSON)),
    };
}

export function BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsToJSON(value?: BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityRelationshipsAppLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(BetaAppClipInvocationRelationshipsBetaAppClipInvocationLocalizationsDataInnerToJSON)),
    };
}

