/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityRelationshipsAppLinks } from './AppAvailabilityRelationshipsAppLinks';
import {
    AppAvailabilityRelationshipsAppLinksFromJSON,
    AppAvailabilityRelationshipsAppLinksFromJSONTyped,
    AppAvailabilityRelationshipsAppLinksToJSON,
} from './AppAvailabilityRelationshipsAppLinks';
import type { AppRelationshipsInAppPurchasesV2DataInner } from './AppRelationshipsInAppPurchasesV2DataInner';
import {
    AppRelationshipsInAppPurchasesV2DataInnerFromJSON,
    AppRelationshipsInAppPurchasesV2DataInnerFromJSONTyped,
    AppRelationshipsInAppPurchasesV2DataInnerToJSON,
} from './AppRelationshipsInAppPurchasesV2DataInner';

/**
 * 
 * @export
 * @interface InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2
 */
export interface InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2 {
    /**
     * 
     * @type {AppAvailabilityRelationshipsAppLinks}
     * @memberof InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2
     */
    links?: AppAvailabilityRelationshipsAppLinks;
    /**
     * 
     * @type {AppRelationshipsInAppPurchasesV2DataInner}
     * @memberof InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2
     */
    data?: AppRelationshipsInAppPurchasesV2DataInner;
}

/**
 * Check if a given object implements the InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2 interface.
 */
export function instanceOfInAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2FromJSON(json: any): InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2 {
    return InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2FromJSONTyped(json, false);
}

export function InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityRelationshipsAppLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppRelationshipsInAppPurchasesV2DataInnerFromJSON(json['data']),
    };
}

export function InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2ToJSON(value?: InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityRelationshipsAppLinksToJSON(value.links),
        'data': AppRelationshipsInAppPurchasesV2DataInnerToJSON(value.data),
    };
}

