export * from './ageRatingDeclarationsApi';
import { AgeRatingDeclarationsApi } from './ageRatingDeclarationsApi';
export * from './appAvailabilitiesApi';
import { AppAvailabilitiesApi } from './appAvailabilitiesApi';
export * from './appCategoriesApi';
import { AppCategoriesApi } from './appCategoriesApi';
export * from './appClipAdvancedExperienceImagesApi';
import { AppClipAdvancedExperienceImagesApi } from './appClipAdvancedExperienceImagesApi';
export * from './appClipAdvancedExperiencesApi';
import { AppClipAdvancedExperiencesApi } from './appClipAdvancedExperiencesApi';
export * from './appClipAppStoreReviewDetailsApi';
import { AppClipAppStoreReviewDetailsApi } from './appClipAppStoreReviewDetailsApi';
export * from './appClipDefaultExperienceLocalizationsApi';
import { AppClipDefaultExperienceLocalizationsApi } from './appClipDefaultExperienceLocalizationsApi';
export * from './appClipDefaultExperiencesApi';
import { AppClipDefaultExperiencesApi } from './appClipDefaultExperiencesApi';
export * from './appClipHeaderImagesApi';
import { AppClipHeaderImagesApi } from './appClipHeaderImagesApi';
export * from './appClipsApi';
import { AppClipsApi } from './appClipsApi';
export * from './appCustomProductPageLocalizationsApi';
import { AppCustomProductPageLocalizationsApi } from './appCustomProductPageLocalizationsApi';
export * from './appCustomProductPageVersionsApi';
import { AppCustomProductPageVersionsApi } from './appCustomProductPageVersionsApi';
export * from './appCustomProductPagesApi';
import { AppCustomProductPagesApi } from './appCustomProductPagesApi';
export * from './appEncryptionDeclarationDocumentsApi';
import { AppEncryptionDeclarationDocumentsApi } from './appEncryptionDeclarationDocumentsApi';
export * from './appEncryptionDeclarationsApi';
import { AppEncryptionDeclarationsApi } from './appEncryptionDeclarationsApi';
export * from './appEventLocalizationsApi';
import { AppEventLocalizationsApi } from './appEventLocalizationsApi';
export * from './appEventScreenshotsApi';
import { AppEventScreenshotsApi } from './appEventScreenshotsApi';
export * from './appEventVideoClipsApi';
import { AppEventVideoClipsApi } from './appEventVideoClipsApi';
export * from './appEventsApi';
import { AppEventsApi } from './appEventsApi';
export * from './appInfoLocalizationsApi';
import { AppInfoLocalizationsApi } from './appInfoLocalizationsApi';
export * from './appInfosApi';
import { AppInfosApi } from './appInfosApi';
export * from './appPreOrdersApi';
import { AppPreOrdersApi } from './appPreOrdersApi';
export * from './appPreviewSetsApi';
import { AppPreviewSetsApi } from './appPreviewSetsApi';
export * from './appPreviewsApi';
import { AppPreviewsApi } from './appPreviewsApi';
export * from './appPricePointsApi';
import { AppPricePointsApi } from './appPricePointsApi';
export * from './appPriceSchedulesApi';
import { AppPriceSchedulesApi } from './appPriceSchedulesApi';
export * from './appScreenshotSetsApi';
import { AppScreenshotSetsApi } from './appScreenshotSetsApi';
export * from './appScreenshotsApi';
import { AppScreenshotsApi } from './appScreenshotsApi';
export * from './appStoreReviewAttachmentsApi';
import { AppStoreReviewAttachmentsApi } from './appStoreReviewAttachmentsApi';
export * from './appStoreReviewDetailsApi';
import { AppStoreReviewDetailsApi } from './appStoreReviewDetailsApi';
export * from './appStoreVersionExperimentTreatmentLocalizationsApi';
import { AppStoreVersionExperimentTreatmentLocalizationsApi } from './appStoreVersionExperimentTreatmentLocalizationsApi';
export * from './appStoreVersionExperimentTreatmentsApi';
import { AppStoreVersionExperimentTreatmentsApi } from './appStoreVersionExperimentTreatmentsApi';
export * from './appStoreVersionExperimentsApi';
import { AppStoreVersionExperimentsApi } from './appStoreVersionExperimentsApi';
export * from './appStoreVersionLocalizationsApi';
import { AppStoreVersionLocalizationsApi } from './appStoreVersionLocalizationsApi';
export * from './appStoreVersionPhasedReleasesApi';
import { AppStoreVersionPhasedReleasesApi } from './appStoreVersionPhasedReleasesApi';
export * from './appStoreVersionPromotionsApi';
import { AppStoreVersionPromotionsApi } from './appStoreVersionPromotionsApi';
export * from './appStoreVersionReleaseRequestsApi';
import { AppStoreVersionReleaseRequestsApi } from './appStoreVersionReleaseRequestsApi';
export * from './appStoreVersionsApi';
import { AppStoreVersionsApi } from './appStoreVersionsApi';
export * from './appsApi';
import { AppsApi } from './appsApi';
export * from './betaAppClipInvocationLocalizationsApi';
import { BetaAppClipInvocationLocalizationsApi } from './betaAppClipInvocationLocalizationsApi';
export * from './betaAppClipInvocationsApi';
import { BetaAppClipInvocationsApi } from './betaAppClipInvocationsApi';
export * from './betaAppLocalizationsApi';
import { BetaAppLocalizationsApi } from './betaAppLocalizationsApi';
export * from './betaAppReviewDetailsApi';
import { BetaAppReviewDetailsApi } from './betaAppReviewDetailsApi';
export * from './betaAppReviewSubmissionsApi';
import { BetaAppReviewSubmissionsApi } from './betaAppReviewSubmissionsApi';
export * from './betaBuildLocalizationsApi';
import { BetaBuildLocalizationsApi } from './betaBuildLocalizationsApi';
export * from './betaGroupsApi';
import { BetaGroupsApi } from './betaGroupsApi';
export * from './betaLicenseAgreementsApi';
import { BetaLicenseAgreementsApi } from './betaLicenseAgreementsApi';
export * from './betaTesterInvitationsApi';
import { BetaTesterInvitationsApi } from './betaTesterInvitationsApi';
export * from './betaTestersApi';
import { BetaTestersApi } from './betaTestersApi';
export * from './buildBetaDetailsApi';
import { BuildBetaDetailsApi } from './buildBetaDetailsApi';
export * from './buildBetaNotificationsApi';
import { BuildBetaNotificationsApi } from './buildBetaNotificationsApi';
export * from './buildBundlesApi';
import { BuildBundlesApi } from './buildBundlesApi';
export * from './buildsApi';
import { BuildsApi } from './buildsApi';
export * from './bundleIdCapabilitiesApi';
import { BundleIdCapabilitiesApi } from './bundleIdCapabilitiesApi';
export * from './bundleIdsApi';
import { BundleIdsApi } from './bundleIdsApi';
export * from './certificatesApi';
import { CertificatesApi } from './certificatesApi';
export * from './ciArtifactsApi';
import { CiArtifactsApi } from './ciArtifactsApi';
export * from './ciBuildActionsApi';
import { CiBuildActionsApi } from './ciBuildActionsApi';
export * from './ciBuildRunsApi';
import { CiBuildRunsApi } from './ciBuildRunsApi';
export * from './ciIssuesApi';
import { CiIssuesApi } from './ciIssuesApi';
export * from './ciMacOsVersionsApi';
import { CiMacOsVersionsApi } from './ciMacOsVersionsApi';
export * from './ciProductsApi';
import { CiProductsApi } from './ciProductsApi';
export * from './ciTestResultsApi';
import { CiTestResultsApi } from './ciTestResultsApi';
export * from './ciWorkflowsApi';
import { CiWorkflowsApi } from './ciWorkflowsApi';
export * from './ciXcodeVersionsApi';
import { CiXcodeVersionsApi } from './ciXcodeVersionsApi';
export * from './customerReviewResponsesApi';
import { CustomerReviewResponsesApi } from './customerReviewResponsesApi';
export * from './customerReviewsApi';
import { CustomerReviewsApi } from './customerReviewsApi';
export * from './devicesApi';
import { DevicesApi } from './devicesApi';
export * from './diagnosticSignaturesApi';
import { DiagnosticSignaturesApi } from './diagnosticSignaturesApi';
export * from './endUserLicenseAgreementsApi';
import { EndUserLicenseAgreementsApi } from './endUserLicenseAgreementsApi';
export * from './financeReportsApi';
import { FinanceReportsApi } from './financeReportsApi';
export * from './gameCenterEnabledVersionsApi';
import { GameCenterEnabledVersionsApi } from './gameCenterEnabledVersionsApi';
export * from './inAppPurchaseAppStoreReviewScreenshotsApi';
import { InAppPurchaseAppStoreReviewScreenshotsApi } from './inAppPurchaseAppStoreReviewScreenshotsApi';
export * from './inAppPurchaseAvailabilitiesApi';
import { InAppPurchaseAvailabilitiesApi } from './inAppPurchaseAvailabilitiesApi';
export * from './inAppPurchaseContentsApi';
import { InAppPurchaseContentsApi } from './inAppPurchaseContentsApi';
export * from './inAppPurchaseLocalizationsApi';
import { InAppPurchaseLocalizationsApi } from './inAppPurchaseLocalizationsApi';
export * from './inAppPurchasePriceSchedulesApi';
import { InAppPurchasePriceSchedulesApi } from './inAppPurchasePriceSchedulesApi';
export * from './inAppPurchaseSubmissionsApi';
import { InAppPurchaseSubmissionsApi } from './inAppPurchaseSubmissionsApi';
export * from './inAppPurchasesApi';
import { InAppPurchasesApi } from './inAppPurchasesApi';
export * from './preReleaseVersionsApi';
import { PreReleaseVersionsApi } from './preReleaseVersionsApi';
export * from './profilesApi';
import { ProfilesApi } from './profilesApi';
export * from './promotedPurchaseImagesApi';
import { PromotedPurchaseImagesApi } from './promotedPurchaseImagesApi';
export * from './promotedPurchasesApi';
import { PromotedPurchasesApi } from './promotedPurchasesApi';
export * from './reviewSubmissionItemsApi';
import { ReviewSubmissionItemsApi } from './reviewSubmissionItemsApi';
export * from './reviewSubmissionsApi';
import { ReviewSubmissionsApi } from './reviewSubmissionsApi';
export * from './routingAppCoveragesApi';
import { RoutingAppCoveragesApi } from './routingAppCoveragesApi';
export * from './salesReportsApi';
import { SalesReportsApi } from './salesReportsApi';
export * from './sandboxTestersApi';
import { SandboxTestersApi } from './sandboxTestersApi';
export * from './sandboxTestersClearPurchaseHistoryRequestApi';
import { SandboxTestersClearPurchaseHistoryRequestApi } from './sandboxTestersClearPurchaseHistoryRequestApi';
export * from './scmGitReferencesApi';
import { ScmGitReferencesApi } from './scmGitReferencesApi';
export * from './scmProvidersApi';
import { ScmProvidersApi } from './scmProvidersApi';
export * from './scmPullRequestsApi';
import { ScmPullRequestsApi } from './scmPullRequestsApi';
export * from './scmRepositoriesApi';
import { ScmRepositoriesApi } from './scmRepositoriesApi';
export * from './subscriptionAppStoreReviewScreenshotsApi';
import { SubscriptionAppStoreReviewScreenshotsApi } from './subscriptionAppStoreReviewScreenshotsApi';
export * from './subscriptionAvailabilitiesApi';
import { SubscriptionAvailabilitiesApi } from './subscriptionAvailabilitiesApi';
export * from './subscriptionGracePeriodsApi';
import { SubscriptionGracePeriodsApi } from './subscriptionGracePeriodsApi';
export * from './subscriptionGroupLocalizationsApi';
import { SubscriptionGroupLocalizationsApi } from './subscriptionGroupLocalizationsApi';
export * from './subscriptionGroupSubmissionsApi';
import { SubscriptionGroupSubmissionsApi } from './subscriptionGroupSubmissionsApi';
export * from './subscriptionGroupsApi';
import { SubscriptionGroupsApi } from './subscriptionGroupsApi';
export * from './subscriptionIntroductoryOffersApi';
import { SubscriptionIntroductoryOffersApi } from './subscriptionIntroductoryOffersApi';
export * from './subscriptionLocalizationsApi';
import { SubscriptionLocalizationsApi } from './subscriptionLocalizationsApi';
export * from './subscriptionOfferCodeCustomCodesApi';
import { SubscriptionOfferCodeCustomCodesApi } from './subscriptionOfferCodeCustomCodesApi';
export * from './subscriptionOfferCodeOneTimeUseCodesApi';
import { SubscriptionOfferCodeOneTimeUseCodesApi } from './subscriptionOfferCodeOneTimeUseCodesApi';
export * from './subscriptionOfferCodesApi';
import { SubscriptionOfferCodesApi } from './subscriptionOfferCodesApi';
export * from './subscriptionPricePointsApi';
import { SubscriptionPricePointsApi } from './subscriptionPricePointsApi';
export * from './subscriptionPricesApi';
import { SubscriptionPricesApi } from './subscriptionPricesApi';
export * from './subscriptionPromotionalOffersApi';
import { SubscriptionPromotionalOffersApi } from './subscriptionPromotionalOffersApi';
export * from './subscriptionSubmissionsApi';
import { SubscriptionSubmissionsApi } from './subscriptionSubmissionsApi';
export * from './subscriptionsApi';
import { SubscriptionsApi } from './subscriptionsApi';
export * from './territoriesApi';
import { TerritoriesApi } from './territoriesApi';
export * from './userInvitationsApi';
import { UserInvitationsApi } from './userInvitationsApi';
export * from './usersApi';
import { UsersApi } from './usersApi';
import * as http from 'http';
export class HttpError extends Error {
    constructor(public response: http.IncomingMessage, public body: any, public statusCode?: number) {
        super('HTTP request failed');
        this.name = 'HttpError';
    }
}
export type { RequestFile } from '../model/models';
export const APIS = [AgeRatingDeclarationsApi, AppAvailabilitiesApi, AppCategoriesApi, AppClipAdvancedExperienceImagesApi, AppClipAdvancedExperiencesApi, AppClipAppStoreReviewDetailsApi, AppClipDefaultExperienceLocalizationsApi, AppClipDefaultExperiencesApi, AppClipHeaderImagesApi, AppClipsApi, AppCustomProductPageLocalizationsApi, AppCustomProductPageVersionsApi, AppCustomProductPagesApi, AppEncryptionDeclarationDocumentsApi, AppEncryptionDeclarationsApi, AppEventLocalizationsApi, AppEventScreenshotsApi, AppEventVideoClipsApi, AppEventsApi, AppInfoLocalizationsApi, AppInfosApi, AppPreOrdersApi, AppPreviewSetsApi, AppPreviewsApi, AppPricePointsApi, AppPriceSchedulesApi, AppScreenshotSetsApi, AppScreenshotsApi, AppStoreReviewAttachmentsApi, AppStoreReviewDetailsApi, AppStoreVersionExperimentTreatmentLocalizationsApi, AppStoreVersionExperimentTreatmentsApi, AppStoreVersionExperimentsApi, AppStoreVersionLocalizationsApi, AppStoreVersionPhasedReleasesApi, AppStoreVersionPromotionsApi, AppStoreVersionReleaseRequestsApi, AppStoreVersionsApi, AppsApi, BetaAppClipInvocationLocalizationsApi, BetaAppClipInvocationsApi, BetaAppLocalizationsApi, BetaAppReviewDetailsApi, BetaAppReviewSubmissionsApi, BetaBuildLocalizationsApi, BetaGroupsApi, BetaLicenseAgreementsApi, BetaTesterInvitationsApi, BetaTestersApi, BuildBetaDetailsApi, BuildBetaNotificationsApi, BuildBundlesApi, BuildsApi, BundleIdCapabilitiesApi, BundleIdsApi, CertificatesApi, CiArtifactsApi, CiBuildActionsApi, CiBuildRunsApi, CiIssuesApi, CiMacOsVersionsApi, CiProductsApi, CiTestResultsApi, CiWorkflowsApi, CiXcodeVersionsApi, CustomerReviewResponsesApi, CustomerReviewsApi, DevicesApi, DiagnosticSignaturesApi, EndUserLicenseAgreementsApi, FinanceReportsApi, GameCenterEnabledVersionsApi, InAppPurchaseAppStoreReviewScreenshotsApi, InAppPurchaseAvailabilitiesApi, InAppPurchaseContentsApi, InAppPurchaseLocalizationsApi, InAppPurchasePriceSchedulesApi, InAppPurchaseSubmissionsApi, InAppPurchasesApi, PreReleaseVersionsApi, ProfilesApi, PromotedPurchaseImagesApi, PromotedPurchasesApi, ReviewSubmissionItemsApi, ReviewSubmissionsApi, RoutingAppCoveragesApi, SalesReportsApi, SandboxTestersApi, SandboxTestersClearPurchaseHistoryRequestApi, ScmGitReferencesApi, ScmProvidersApi, ScmPullRequestsApi, ScmRepositoriesApi, SubscriptionAppStoreReviewScreenshotsApi, SubscriptionAvailabilitiesApi, SubscriptionGracePeriodsApi, SubscriptionGroupLocalizationsApi, SubscriptionGroupSubmissionsApi, SubscriptionGroupsApi, SubscriptionIntroductoryOffersApi, SubscriptionLocalizationsApi, SubscriptionOfferCodeCustomCodesApi, SubscriptionOfferCodeOneTimeUseCodesApi, SubscriptionOfferCodesApi, SubscriptionPricePointsApi, SubscriptionPricesApi, SubscriptionPromotionalOffersApi, SubscriptionSubmissionsApi, SubscriptionsApi, TerritoriesApi, UserInvitationsApi, UsersApi];
