/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { AppClipAppStoreReviewDetailResponse, AppClipDefaultExperienceCreateRequest, AppClipDefaultExperienceLocalizationsResponse, AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequest, AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageResponse, AppClipDefaultExperienceResponse, AppClipDefaultExperienceUpdateRequest, AppStoreVersionResponse, ErrorResponse, } from '../models';
import { AppClipAppStoreReviewDetailResponseFromJSON, AppClipAppStoreReviewDetailResponseToJSON, AppClipDefaultExperienceCreateRequestFromJSON, AppClipDefaultExperienceCreateRequestToJSON, AppClipDefaultExperienceLocalizationsResponseFromJSON, AppClipDefaultExperienceLocalizationsResponseToJSON, AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequestFromJSON, AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequestToJSON, AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageResponseFromJSON, AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageResponseToJSON, AppClipDefaultExperienceResponseFromJSON, AppClipDefaultExperienceResponseToJSON, AppClipDefaultExperienceUpdateRequestFromJSON, AppClipDefaultExperienceUpdateRequestToJSON, AppStoreVersionResponseFromJSON, AppStoreVersionResponseToJSON, ErrorResponseFromJSON, ErrorResponseToJSON, } from '../models';
export interface AppClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedRequest {
    id: string;
    fieldsAppClipAppStoreReviewDetails?: Array<AppClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedFieldsAppClipAppStoreReviewDetailsEnum>;
    fieldsAppClipDefaultExperiences?: Array<AppClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedFieldsAppClipDefaultExperiencesEnum>;
    include?: Array<AppClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedIncludeEnum>;
}
export interface AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedRequest {
    id: string;
    filterLocale?: Array<string>;
    fieldsAppClipDefaultExperiences?: Array<AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedFieldsAppClipDefaultExperiencesEnum>;
    fieldsAppClipDefaultExperienceLocalizations?: Array<AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedFieldsAppClipDefaultExperienceLocalizationsEnum>;
    fieldsAppClipHeaderImages?: Array<AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedFieldsAppClipHeaderImagesEnum>;
    limit?: number;
    include?: Array<AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedIncludeEnum>;
}
export interface AppClipDefaultExperiencesCreateInstanceRequest {
    appClipDefaultExperienceCreateRequest: AppClipDefaultExperienceCreateRequest;
}
export interface AppClipDefaultExperiencesDeleteInstanceRequest {
    id: string;
}
export interface AppClipDefaultExperiencesGetInstanceRequest {
    id: string;
    fieldsAppClipDefaultExperiences?: Array<AppClipDefaultExperiencesGetInstanceFieldsAppClipDefaultExperiencesEnum>;
    include?: Array<AppClipDefaultExperiencesGetInstanceIncludeEnum>;
    fieldsAppClipAppStoreReviewDetails?: Array<AppClipDefaultExperiencesGetInstanceFieldsAppClipAppStoreReviewDetailsEnum>;
    fieldsAppStoreVersions?: Array<AppClipDefaultExperiencesGetInstanceFieldsAppStoreVersionsEnum>;
    fieldsAppClipDefaultExperienceLocalizations?: Array<AppClipDefaultExperiencesGetInstanceFieldsAppClipDefaultExperienceLocalizationsEnum>;
    limitAppClipDefaultExperienceLocalizations?: number;
}
export interface AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedRequest {
    id: string;
    fieldsAppStoreVersionExperiments?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreVersionExperimentsEnum>;
    fieldsAgeRatingDeclarations?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAgeRatingDeclarationsEnum>;
    fieldsAppStoreVersionSubmissions?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreVersionSubmissionsEnum>;
    fieldsAppStoreReviewDetails?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreReviewDetailsEnum>;
    fieldsAppStoreVersions?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreVersionsEnum>;
    fieldsApps?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppsEnum>;
    fieldsRoutingAppCoverages?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsRoutingAppCoveragesEnum>;
    fieldsAppClipDefaultExperiences?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppClipDefaultExperiencesEnum>;
    fieldsAppStoreVersionPhasedReleases?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreVersionPhasedReleasesEnum>;
    fieldsBuilds?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsBuildsEnum>;
    fieldsAppStoreVersionLocalizations?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreVersionLocalizationsEnum>;
    limitAppStoreVersionLocalizations?: number;
    limitAppStoreVersionExperiments?: number;
    include?: Array<AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedIncludeEnum>;
}
export interface AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelationshipRequest {
    id: string;
}
export interface AppClipDefaultExperiencesReleaseWithAppStoreVersionUpdateToOneRelationshipRequest {
    id: string;
    appClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequest: AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequest;
}
export interface AppClipDefaultExperiencesUpdateInstanceRequest {
    id: string;
    appClipDefaultExperienceUpdateRequest: AppClipDefaultExperienceUpdateRequest;
}
/**
 *
 */
export class AppClipDefaultExperiencesApi extends runtime.BaseAPI {
    /**
     */
    async appClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedRaw(requestParameters: AppClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppClipAppStoreReviewDetailResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling appClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelated.');
        }
        const queryParameters: any = {};
        if (requestParameters.fieldsAppClipAppStoreReviewDetails) {
            queryParameters['fields[appClipAppStoreReviewDetails]'] = requestParameters.fieldsAppClipAppStoreReviewDetails.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppClipDefaultExperiences) {
            queryParameters['fields[appClipDefaultExperiences]'] = requestParameters.fieldsAppClipDefaultExperiences.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.include) {
            queryParameters['include'] = requestParameters.include.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        const headerParameters: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itcBearerToken", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/appClipDefaultExperiences/{id}/appClipAppStoreReviewDetail`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => AppClipAppStoreReviewDetailResponseFromJSON(jsonValue));
    }
    /**
     */
    async appClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelated(requestParameters: AppClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppClipAppStoreReviewDetailResponse> {
        const response = await this.appClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     */
    async appClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedRaw(requestParameters: AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppClipDefaultExperienceLocalizationsResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling appClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelated.');
        }
        const queryParameters: any = {};
        if (requestParameters.filterLocale) {
            queryParameters['filter[locale]'] = requestParameters.filterLocale.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppClipDefaultExperiences) {
            queryParameters['fields[appClipDefaultExperiences]'] = requestParameters.fieldsAppClipDefaultExperiences.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppClipDefaultExperienceLocalizations) {
            queryParameters['fields[appClipDefaultExperienceLocalizations]'] = requestParameters.fieldsAppClipDefaultExperienceLocalizations.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppClipHeaderImages) {
            queryParameters['fields[appClipHeaderImages]'] = requestParameters.fieldsAppClipHeaderImages.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }
        if (requestParameters.include) {
            queryParameters['include'] = requestParameters.include.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        const headerParameters: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itcBearerToken", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/appClipDefaultExperiences/{id}/appClipDefaultExperienceLocalizations`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => AppClipDefaultExperienceLocalizationsResponseFromJSON(jsonValue));
    }
    /**
     */
    async appClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelated(requestParameters: AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppClipDefaultExperienceLocalizationsResponse> {
        const response = await this.appClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     */
    async appClipDefaultExperiencesCreateInstanceRaw(requestParameters: AppClipDefaultExperiencesCreateInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppClipDefaultExperienceResponse>> {
        if (requestParameters.appClipDefaultExperienceCreateRequest === null || requestParameters.appClipDefaultExperienceCreateRequest === undefined) {
            throw new runtime.RequiredError('appClipDefaultExperienceCreateRequest', 'Required parameter requestParameters.appClipDefaultExperienceCreateRequest was null or undefined when calling appClipDefaultExperiencesCreateInstance.');
        }
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itcBearerToken", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/appClipDefaultExperiences`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AppClipDefaultExperienceCreateRequestToJSON(requestParameters.appClipDefaultExperienceCreateRequest),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => AppClipDefaultExperienceResponseFromJSON(jsonValue));
    }
    /**
     */
    async appClipDefaultExperiencesCreateInstance(requestParameters: AppClipDefaultExperiencesCreateInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppClipDefaultExperienceResponse> {
        const response = await this.appClipDefaultExperiencesCreateInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     */
    async appClipDefaultExperiencesDeleteInstanceRaw(requestParameters: AppClipDefaultExperiencesDeleteInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling appClipDefaultExperiencesDeleteInstance.');
        }
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itcBearerToken", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/appClipDefaultExperiences/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     */
    async appClipDefaultExperiencesDeleteInstance(requestParameters: AppClipDefaultExperiencesDeleteInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.appClipDefaultExperiencesDeleteInstanceRaw(requestParameters, initOverrides);
    }
    /**
     */
    async appClipDefaultExperiencesGetInstanceRaw(requestParameters: AppClipDefaultExperiencesGetInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppClipDefaultExperienceResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling appClipDefaultExperiencesGetInstance.');
        }
        const queryParameters: any = {};
        if (requestParameters.fieldsAppClipDefaultExperiences) {
            queryParameters['fields[appClipDefaultExperiences]'] = requestParameters.fieldsAppClipDefaultExperiences.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.include) {
            queryParameters['include'] = requestParameters.include.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppClipAppStoreReviewDetails) {
            queryParameters['fields[appClipAppStoreReviewDetails]'] = requestParameters.fieldsAppClipAppStoreReviewDetails.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppStoreVersions) {
            queryParameters['fields[appStoreVersions]'] = requestParameters.fieldsAppStoreVersions.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppClipDefaultExperienceLocalizations) {
            queryParameters['fields[appClipDefaultExperienceLocalizations]'] = requestParameters.fieldsAppClipDefaultExperienceLocalizations.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.limitAppClipDefaultExperienceLocalizations !== undefined) {
            queryParameters['limit[appClipDefaultExperienceLocalizations]'] = requestParameters.limitAppClipDefaultExperienceLocalizations;
        }
        const headerParameters: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itcBearerToken", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/appClipDefaultExperiences/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => AppClipDefaultExperienceResponseFromJSON(jsonValue));
    }
    /**
     */
    async appClipDefaultExperiencesGetInstance(requestParameters: AppClipDefaultExperiencesGetInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppClipDefaultExperienceResponse> {
        const response = await this.appClipDefaultExperiencesGetInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     */
    async appClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedRaw(requestParameters: AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppStoreVersionResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling appClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelated.');
        }
        const queryParameters: any = {};
        if (requestParameters.fieldsAppStoreVersionExperiments) {
            queryParameters['fields[appStoreVersionExperiments]'] = requestParameters.fieldsAppStoreVersionExperiments.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAgeRatingDeclarations) {
            queryParameters['fields[ageRatingDeclarations]'] = requestParameters.fieldsAgeRatingDeclarations.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppStoreVersionSubmissions) {
            queryParameters['fields[appStoreVersionSubmissions]'] = requestParameters.fieldsAppStoreVersionSubmissions.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppStoreReviewDetails) {
            queryParameters['fields[appStoreReviewDetails]'] = requestParameters.fieldsAppStoreReviewDetails.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppStoreVersions) {
            queryParameters['fields[appStoreVersions]'] = requestParameters.fieldsAppStoreVersions.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsApps) {
            queryParameters['fields[apps]'] = requestParameters.fieldsApps.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsRoutingAppCoverages) {
            queryParameters['fields[routingAppCoverages]'] = requestParameters.fieldsRoutingAppCoverages.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppClipDefaultExperiences) {
            queryParameters['fields[appClipDefaultExperiences]'] = requestParameters.fieldsAppClipDefaultExperiences.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppStoreVersionPhasedReleases) {
            queryParameters['fields[appStoreVersionPhasedReleases]'] = requestParameters.fieldsAppStoreVersionPhasedReleases.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsBuilds) {
            queryParameters['fields[builds]'] = requestParameters.fieldsBuilds.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.fieldsAppStoreVersionLocalizations) {
            queryParameters['fields[appStoreVersionLocalizations]'] = requestParameters.fieldsAppStoreVersionLocalizations.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        if (requestParameters.limitAppStoreVersionLocalizations !== undefined) {
            queryParameters['limit[appStoreVersionLocalizations]'] = requestParameters.limitAppStoreVersionLocalizations;
        }
        if (requestParameters.limitAppStoreVersionExperiments !== undefined) {
            queryParameters['limit[appStoreVersionExperiments]'] = requestParameters.limitAppStoreVersionExperiments;
        }
        if (requestParameters.include) {
            queryParameters['include'] = requestParameters.include.join(runtime.COLLECTION_FORMATS["csv"]);
        }
        const headerParameters: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itcBearerToken", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/appClipDefaultExperiences/{id}/releaseWithAppStoreVersion`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => AppStoreVersionResponseFromJSON(jsonValue));
    }
    /**
     */
    async appClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelated(requestParameters: AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppStoreVersionResponse> {
        const response = await this.appClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     */
    async appClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelationshipRaw(requestParameters: AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling appClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelationship.');
        }
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itcBearerToken", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/appClipDefaultExperiences/{id}/relationships/releaseWithAppStoreVersion`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageResponseFromJSON(jsonValue));
    }
    /**
     */
    async appClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelationship(requestParameters: AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageResponse> {
        const response = await this.appClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelationshipRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     */
    async appClipDefaultExperiencesReleaseWithAppStoreVersionUpdateToOneRelationshipRaw(requestParameters: AppClipDefaultExperiencesReleaseWithAppStoreVersionUpdateToOneRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling appClipDefaultExperiencesReleaseWithAppStoreVersionUpdateToOneRelationship.');
        }
        if (requestParameters.appClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequest === null || requestParameters.appClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequest === undefined) {
            throw new runtime.RequiredError('appClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequest', 'Required parameter requestParameters.appClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequest was null or undefined when calling appClipDefaultExperiencesReleaseWithAppStoreVersionUpdateToOneRelationship.');
        }
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itcBearerToken", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/appClipDefaultExperiences/{id}/relationships/releaseWithAppStoreVersion`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequestToJSON(requestParameters.appClipDefaultExperienceReleaseWithAppStoreVersionLinkageRequest),
        }, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     */
    async appClipDefaultExperiencesReleaseWithAppStoreVersionUpdateToOneRelationship(requestParameters: AppClipDefaultExperiencesReleaseWithAppStoreVersionUpdateToOneRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.appClipDefaultExperiencesReleaseWithAppStoreVersionUpdateToOneRelationshipRaw(requestParameters, initOverrides);
    }
    /**
     */
    async appClipDefaultExperiencesUpdateInstanceRaw(requestParameters: AppClipDefaultExperiencesUpdateInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppClipDefaultExperienceResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling appClipDefaultExperiencesUpdateInstance.');
        }
        if (requestParameters.appClipDefaultExperienceUpdateRequest === null || requestParameters.appClipDefaultExperienceUpdateRequest === undefined) {
            throw new runtime.RequiredError('appClipDefaultExperienceUpdateRequest', 'Required parameter requestParameters.appClipDefaultExperienceUpdateRequest was null or undefined when calling appClipDefaultExperiencesUpdateInstance.');
        }
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itcBearerToken", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/appClipDefaultExperiences/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AppClipDefaultExperienceUpdateRequestToJSON(requestParameters.appClipDefaultExperienceUpdateRequest),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => AppClipDefaultExperienceResponseFromJSON(jsonValue));
    }
    /**
     */
    async appClipDefaultExperiencesUpdateInstance(requestParameters: AppClipDefaultExperiencesUpdateInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppClipDefaultExperienceResponse> {
        const response = await this.appClipDefaultExperiencesUpdateInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
/**
 * @export
 */
export type AppClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedFieldsAppClipAppStoreReviewDetailsEnum = 'appClipDefaultExperience' | 'invocationUrls';;
/**
 * @export
 */
export type AppClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedFieldsAppClipDefaultExperiencesEnum = 'action' | 'appClip' | 'appClipAppStoreReviewDetail' | 'appClipDefaultExperienceLocalizations' | 'appClipDefaultExperienceTemplate' | 'releaseWithAppStoreVersion';;
/**
 * @export
 */
export type AppClipDefaultExperiencesAppClipAppStoreReviewDetailGetToOneRelatedIncludeEnum = 'appClipDefaultExperience';;
/**
 * @export
 */
export type AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedFieldsAppClipDefaultExperiencesEnum = 'action' | 'appClip' | 'appClipAppStoreReviewDetail' | 'appClipDefaultExperienceLocalizations' | 'appClipDefaultExperienceTemplate' | 'releaseWithAppStoreVersion';;
/**
 * @export
 */
export type AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedFieldsAppClipDefaultExperienceLocalizationsEnum = 'appClipDefaultExperience' | 'appClipHeaderImage' | 'locale' | 'subtitle';;
/**
 * @export
 */
export type AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedFieldsAppClipHeaderImagesEnum = 'appClipDefaultExperienceLocalization' | 'assetDeliveryState' | 'fileName' | 'fileSize' | 'imageAsset' | 'sourceFileChecksum' | 'uploadOperations' | 'uploaded';;
/**
 * @export
 */
export type AppClipDefaultExperiencesAppClipDefaultExperienceLocalizationsGetToManyRelatedIncludeEnum = 'appClipDefaultExperience' | 'appClipHeaderImage';;
/**
 * @export
 */
export type AppClipDefaultExperiencesGetInstanceFieldsAppClipDefaultExperiencesEnum = 'action' | 'appClip' | 'appClipAppStoreReviewDetail' | 'appClipDefaultExperienceLocalizations' | 'appClipDefaultExperienceTemplate' | 'releaseWithAppStoreVersion';;
/**
 * @export
 */
export type AppClipDefaultExperiencesGetInstanceIncludeEnum = 'appClip' | 'appClipAppStoreReviewDetail' | 'appClipDefaultExperienceLocalizations' | 'releaseWithAppStoreVersion';;
/**
 * @export
 */
export type AppClipDefaultExperiencesGetInstanceFieldsAppClipAppStoreReviewDetailsEnum = 'appClipDefaultExperience' | 'invocationUrls';;
/**
 * @export
 */
export type AppClipDefaultExperiencesGetInstanceFieldsAppStoreVersionsEnum = 'ageRatingDeclaration' | 'app' | 'appClipDefaultExperience' | 'appStoreReviewDetail' | 'appStoreState' | 'appStoreVersionExperiments' | 'appStoreVersionLocalizations' | 'appStoreVersionPhasedRelease' | 'appStoreVersionSubmission' | 'build' | 'copyright' | 'createdDate' | 'customerReviews' | 'downloadable' | 'earliestReleaseDate' | 'platform' | 'releaseType' | 'routingAppCoverage' | 'versionString';;
/**
 * @export
 */
export type AppClipDefaultExperiencesGetInstanceFieldsAppClipDefaultExperienceLocalizationsEnum = 'appClipDefaultExperience' | 'appClipHeaderImage' | 'locale' | 'subtitle';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreVersionExperimentsEnum = 'appStoreVersion' | 'appStoreVersionExperimentTreatments' | 'endDate' | 'name' | 'reviewRequired' | 'startDate' | 'started' | 'state' | 'trafficProportion';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAgeRatingDeclarationsEnum = 'alcoholTobaccoOrDrugUseOrReferences' | 'contests' | 'gambling' | 'gamblingAndContests' | 'gamblingSimulated' | 'horrorOrFearThemes' | 'kidsAgeBand' | 'matureOrSuggestiveThemes' | 'medicalOrTreatmentInformation' | 'profanityOrCrudeHumor' | 'seventeenPlus' | 'sexualContentGraphicAndNudity' | 'sexualContentOrNudity' | 'unrestrictedWebAccess' | 'violenceCartoonOrFantasy' | 'violenceRealistic' | 'violenceRealisticProlongedGraphicOrSadistic';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreVersionSubmissionsEnum = 'appStoreVersion';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreReviewDetailsEnum = 'appStoreReviewAttachments' | 'appStoreVersion' | 'contactEmail' | 'contactFirstName' | 'contactLastName' | 'contactPhone' | 'demoAccountName' | 'demoAccountPassword' | 'demoAccountRequired' | 'notes';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreVersionsEnum = 'ageRatingDeclaration' | 'app' | 'appClipDefaultExperience' | 'appStoreReviewDetail' | 'appStoreState' | 'appStoreVersionExperiments' | 'appStoreVersionLocalizations' | 'appStoreVersionPhasedRelease' | 'appStoreVersionSubmission' | 'build' | 'copyright' | 'createdDate' | 'customerReviews' | 'downloadable' | 'earliestReleaseDate' | 'platform' | 'releaseType' | 'routingAppCoverage' | 'versionString';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppsEnum = 'appAvailability' | 'appClips' | 'appCustomProductPages' | 'appEvents' | 'appInfos' | 'appPricePoints' | 'appPriceSchedule' | 'appStoreVersions' | 'availableInNewTerritories' | 'availableTerritories' | 'betaAppLocalizations' | 'betaAppReviewDetail' | 'betaGroups' | 'betaLicenseAgreement' | 'betaTesters' | 'builds' | 'bundleId' | 'ciProduct' | 'contentRightsDeclaration' | 'customerReviews' | 'endUserLicenseAgreement' | 'gameCenterEnabledVersions' | 'inAppPurchases' | 'inAppPurchasesV2' | 'isOrEverWasMadeForKids' | 'name' | 'perfPowerMetrics' | 'preOrder' | 'preReleaseVersions' | 'pricePoints' | 'prices' | 'primaryLocale' | 'promotedPurchases' | 'reviewSubmissions' | 'sku' | 'subscriptionGracePeriod' | 'subscriptionGroups' | 'subscriptionStatusUrl' | 'subscriptionStatusUrlForSandbox' | 'subscriptionStatusUrlVersion' | 'subscriptionStatusUrlVersionForSandbox';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsRoutingAppCoveragesEnum = 'appStoreVersion' | 'assetDeliveryState' | 'fileName' | 'fileSize' | 'sourceFileChecksum' | 'uploadOperations' | 'uploaded';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppClipDefaultExperiencesEnum = 'action' | 'appClip' | 'appClipAppStoreReviewDetail' | 'appClipDefaultExperienceLocalizations' | 'appClipDefaultExperienceTemplate' | 'releaseWithAppStoreVersion';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreVersionPhasedReleasesEnum = 'appStoreVersion' | 'currentDayNumber' | 'phasedReleaseState' | 'startDate' | 'totalPauseDuration';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsBuildsEnum = 'app' | 'appEncryptionDeclaration' | 'appStoreVersion' | 'betaAppReviewSubmission' | 'betaBuildLocalizations' | 'betaGroups' | 'buildAudienceType' | 'buildBetaDetail' | 'buildBundles' | 'computedMinMacOsVersion' | 'diagnosticSignatures' | 'expirationDate' | 'expired' | 'iconAssetToken' | 'icons' | 'individualTesters' | 'lsMinimumSystemVersion' | 'minOsVersion' | 'perfPowerMetrics' | 'preReleaseVersion' | 'processingState' | 'uploadedDate' | 'usesNonExemptEncryption' | 'version';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedFieldsAppStoreVersionLocalizationsEnum = 'appPreviewSets' | 'appScreenshotSets' | 'appStoreVersion' | 'description' | 'keywords' | 'locale' | 'marketingUrl' | 'promotionalText' | 'supportUrl' | 'whatsNew';;
/**
 * @export
 */
export type AppClipDefaultExperiencesReleaseWithAppStoreVersionGetToOneRelatedIncludeEnum = 'ageRatingDeclaration' | 'app' | 'appClipDefaultExperience' | 'appStoreReviewDetail' | 'appStoreVersionExperiments' | 'appStoreVersionLocalizations' | 'appStoreVersionPhasedRelease' | 'appStoreVersionSubmission' | 'build' | 'routingAppCoverage';;
